const Lab = {
  "Lab": "Escolha o laboratório",
  "LBCT": "Laboratório de Biologia Celular e Tecidual",
  "LBR": "Laboratório de Biologia do Reconhecer",
  "LBT": "Laboratório  de Biotecnologia",
  "LCA": "Laboratório  de Ciências Ambientais",
  "LFBM": "Laboratório  de Fisiologia e Bioquímica de Microorganismos",
  "LQFPP": "Laboratório  de Química e Funções de Proteínas e Peptídeos",
  "LEAG": "Laboratório  de Engenharia Agrícola",
  "LEF": "Laboratório  de Entomologia e Fitopatologia" ,
  "LRMGA": "Laboratório de Reprodução e Melhoramento Genético Animal",
  "LSA": "Laboratório  de Sanidade Animal",
  "LSOL": "Laboratório de Solos",
  "LTA": "Laboratório  de Tecnologia de Alimentos",
  "LZO": "Laboratório de Zootecnia",
  "LMGV": "Laboratório de Melhoramento Genético Vegetal",
  "LCCA": "Laboratório de Clínica e Cirurgia Animal",
  "LMPA": "Laboratório de Morfologia e Patologia Animal",
  "LFIT": "Laboratório  de Fitotecnia",
  "LCL": "Laboratório de Cognição e Linguagem",
  "LEEL": "Laboratório  de Estudo da Educação e Linguagem",
  "LESCE": "Laboratório  de Estudo da Sociedade Civil e do Estado",
  "LEEA": "Laboratório de Estudo do Espaço Antrópico",
  "LGPP": "Laboratório de Gestão e Políticas Públicas",
  "LCFIS": "Laboratório  de Ciências Físicas",
  "LCMAT": "Laboratório  de Ciências Matemáticas", 
  "LCQUI": "Laboratório  de Ciências Químicas",
  "LECIV": "Laboratório  de Engenharia Civil",
  "LENEP": "Laboratório  de Engenharia de Exploração de Petróleo",
  "LEPROD":"Laboratório  de Engenharia de Produção",
  "LAMAV": "Laboratório  de Materiais Avançados",
  "LAMET": "Laboratório de Meteorologia",
}

export default Lab;